#!/usr/bin/env ruby

puts "Project Name:"

@project_name = gets().chomp

@dirs   = %w{lib spec}
@files  = %w{README.md .rspec Guardfile .gitignore spec/helper.rb}

@dirs.each {|dir| `mkdir #{dir}` }
@files.each{|file| `touch #{file}` }

GIT_IGNORE = <<-TEXT
*.swp
*.swo
*.orig
.DS_Store
TEXT

SPEC_OPTS = <<-TEXT
--colour
--format progress
TEXT

GUARDFILE = %q[
guard 'rspec', :version => 2 do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }

  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$}) { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch(%r{^spec/support/(.+)\.rb$}) { "spec" }
  watch('spec/helper.rb') { "spec" }
end
]

SPEC_HELPER = <<-RUBY
$:.unshift File.join(File.dirname(__FILE__), '..', 'lib')

RSpec.configure do |config|
    
end
RUBY

File.open('Guardfile','w') {|f| f.write GUARDFILE }
File.open('.gitignore','w') {|f| f.write GIT_IGNORE }
File.open('.rspec','w') {|f| f.write SPEC_OPTS }
File.open('spec/helper.rb','w') {|f| f.write SPEC_HELPER }

p `rvm --rvmrc 1.9.2@#{@project_name}`
`cd .. && cd -`
p `gem install rspec guard-rspec`

puts "done."
